development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:47c66c987b0dadd5ea90a2d038111f84@pike.redistogo.com:10889/

  channel_prefix: YallaNotlob_production
